apiVersion: v1
kind: Service
metadata:
  name: despacho-backend
  labels:
    app: despacho-backend
spec:
  type: LoadBalancer
  selector:
    app: despacho-backend
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP